apiVersion: integration/v1
kind: Step
name: azureresourcemanager-template-deploy
version: 3
summary: Deploy ARM / Bicep template

description: |
  This step deploys an Azure Resource Manager or Bicep template.

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/azure-step-azureresourcemanager-template-deploy

schemas:
  spec:
    source: file
    file: spec.schema.json

examples:
- summary: Deploy an Azure Resource Manager / Bicep template
  content:
    apiVersion: v1
    kind: Step
    name: deploy-template
    image: relaysh/azure-step-azureresourcemanager-template-deploy
    spec:
      azure: ${connections.azure.my-azure-account}
      deploymentName: ${parameters.deploymentName}
      location: ${parameters.location}
      templateFile: ${parameters.pathToTemplateJson}
      # the template can also be a Bicep file
      # templateFile: !Parameter pathToTemplateBicep
      git:
        connection: ${connection.ssh.my-ssh-connection}
        name: ${parameters.repositoryName}
        branch: ${parameters.branch}
        repository: ${parameters.repository}
      parameters:
        first: example-1
        second: example-2
